#!/usr/bin/env bash
# client-page: publish pages with saved answers to https://<host>/<uuid> on Cloudflare (Worker + D1).
#
# Needs no Cloudflare CLI (no wrangler, no cloudflared): it calls Cloudflare's REST API with curl.
# Start with `doctor`: it checks every prerequisite and prints the next step for anything missing.
#
# Secrets never appear on a command line; they reach curl on stdin (-K -). They are kept in macOS
# Keychain (account "client-page"), or, where there is no Keychain, in mode-600 files in the config dir:
#   client-page-cloudflare-token  the Cloudflare API token the user creates (doctor explains how)
#   client-page-admin-token       generated by `setup`; the Worker's ADMIN_TOKEN secret
# Non-secret settings (host, account, zone and database ids) live in ~/.config/client-page/config.json.
set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONF_DIR="${CLIENT_PAGE_CONFIG_DIR:-$HOME/.config/client-page}"
CONF="$CONF_DIR/config.json"
NAME_DEFAULT="client-page"          # Worker script name and D1 database name
COMPAT_DATE="2026-09-01"
KC_ACCOUNT="client-page"
KC_CF="client-page-cloudflare-token"
KC_ADMIN="client-page-admin-token"
API="https://api.cloudflare.com/client/v4"

die() { echo "client-page: $*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "needs '$1' on PATH; run: $0 doctor"; }
have() { command -v "$1" >/dev/null 2>&1; }

# ---------- secrets ----------

use_keychain() { [[ "${CLIENT_PAGE_SECRET_STORE:-}" != file ]] && have security; }
secret_file() { printf '%s/%s.secret' "$CONF_DIR" "$1"; }

secret_get() {
  # Tests set CLIENT_PAGE_TEST_SECRETS=1 and override a secret through CLIENT_PAGE_CF_TOKEN or
  # CLIENT_PAGE_ADMIN_TOKEN (set but empty means "not saved"); an unset variable uses the real store.
  if [[ "${CLIENT_PAGE_TEST_SECRETS:-}" == 1 ]]; then
    if [[ "$1" == "$KC_CF" && -n "${CLIENT_PAGE_CF_TOKEN+set}" ]]; then printf '%s' "$CLIENT_PAGE_CF_TOKEN"; return 0; fi
    if [[ "$1" == "$KC_ADMIN" && -n "${CLIENT_PAGE_ADMIN_TOKEN+set}" ]]; then printf '%s' "$CLIENT_PAGE_ADMIN_TOKEN"; return 0; fi
  fi
  if use_keychain; then
    security find-generic-password -a "$KC_ACCOUNT" -s "$1" -w 2>/dev/null || true
  elif [[ -f "$(secret_file "$1")" ]]; then
    cat "$(secret_file "$1")"
  fi
}

# Stores a newly generated secret (only the admin token; the user stores the Cloudflare token).
secret_set_random() {
  if use_keychain; then
    security add-generic-password -a "$KC_ACCOUNT" -s "$1" -w "$(openssl rand -hex 32)" -U
  else
    ( umask 077; mkdir -p "$CONF_DIR"; openssl rand -hex 32 | tr -d '\n' >"$(secret_file "$1")" )
  fi
}

where_secrets() { if use_keychain; then echo "macOS Keychain"; else echo "files in $CONF_DIR (mode 600)"; fi; }

# The command a user runs in their own terminal to save a secret; it prompts, so nothing is echoed.
save_secret_cmd() {
  if use_keychain; then
    echo "security add-generic-password -a $KC_ACCOUNT -s $1 -U -w"
  else
    echo "( umask 077; mkdir -p $CONF_DIR; read -rsp 'Paste token: ' t; echo; printf '%s' \"\$t\" > $(secret_file "$1") )"
  fi
}

# ---------- config ----------

conf_get() { [[ -f "$CONF" ]] && jq -r --arg k "$1" '.[$k] // empty' "$CONF" || true; }
conf_set() {
  mkdir -p "$CONF_DIR"
  local tmp; tmp="$(mktemp)"
  if [[ -f "$CONF" ]]; then jq --arg k "$1" --arg v "$2" '.[$k] = $v' "$CONF" >"$tmp"
  else jq -n --arg k "$1" --arg v "$2" '{($k): $v}' >"$tmp"; fi
  mv "$tmp" "$CONF"; chmod 600 "$CONF"
}
host() { conf_get host; }
require_host() {
  local h; h="$(host)"
  [[ -n "$h" ]] || die "no site set up yet. Run: $0 doctor docs.<your-domain>"
  printf '%s' "$h"
}
# Base URL of the site; CLIENT_PAGE_BASE overrides it (tests point it at a local server).
site() { if [[ -n "${CLIENT_PAGE_BASE:-}" ]]; then printf '%s' "$CLIENT_PAGE_BASE"; else printf 'https://%s' "$(require_host)"; fi; }
worker_name() { local w; w="$(conf_get worker)"; printf '%s' "${w:-$NAME_DEFAULT}"; }
require_conf() { local v; v="$(conf_get "$1")"; [[ -n "$v" ]] || die "missing '$1' in $CONF; run: $0 setup"; printf '%s' "$v"; }

# ---------- Cloudflare API ----------

# Cloudflare REST call that never exits: prints the JSON body; returns 0 only if Cloudflare says success.
cf_try() {
  local method="$1" path="$2"; shift 2
  local tok; tok="$(secret_get "$KC_CF")"
  [[ -n "$tok" ]] || { echo '{"success":false,"errors":[{"code":0,"message":"no token saved"}]}'; return 1; }
  local out
  out="$(printf 'header = "Authorization: Bearer %s"\n' "$tok" | curl -sS -m 30 -K - -X "$method" "$API$path" "$@" 2>/dev/null)" \
    || { echo '{"success":false,"errors":[{"code":0,"message":"could not reach api.cloudflare.com"}]}'; return 1; }
  printf '%s' "$out"
  [[ "$(jq -r '.success // false' <<<"$out" 2>/dev/null)" == "true" ]]
}

# Cloudflare REST call that exits with a readable explanation on failure.
cf() {
  local method="$1" path="$2" out
  [[ -n "$(secret_get "$KC_CF")" ]] || die "no Cloudflare API token saved. Run: $0 doctor"
  if out="$(cf_try "$@")"; then printf '%s' "$out"; return 0; fi
  jq -r '(.errors // []) | map("  Cloudflare: \(.code) \(.message)") | join("\n")' <<<"$out" >&2 2>/dev/null || printf '%s\n' "$out" >&2
  if grep -Eq '"code": ?(10000|9109|10001)[,}]' <<<"$out"; then
    echo "  The token is missing a permission for this step. Run: $0 doctor" >&2
  fi
  die "Cloudflare refused: $method $path"
}

# Admin call to the deployed Worker. $3 is an optional JSON body file.
admin() {
  local method="$1" path="$2" body="${3:-}"
  local tok; tok="$(secret_get "$KC_ADMIN")"
  [[ -n "$tok" ]] || die "no admin token saved; run: $0 setup"
  local args=(-sS -X "$method" "$(site)/_admin$path" -H "content-type: application/json" -w $'\n%{http_code}')
  [[ -n "$body" ]] && args+=(--data-binary "@$body")
  local out code
  out="$(printf 'header = "Authorization: Bearer %s"\n' "$tok" | curl -K - "${args[@]}")" || die "request failed: $method $path (is the site up? $0 doctor)"
  code="${out##*$'\n'}"; out="${out%$'\n'*}"
  if [[ "$code" != 2* ]]; then printf '%s\n' "$out" >&2; die "admin API answered HTTP $code"; fi
  printf '%s\n' "$out"
}

uuid_ok() { [[ "$1" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$ ]] || die "not a page id: $1"; }

# Finds the Cloudflare zone that owns HOST by trying each parent name (works for example.co.uk too).
# Prints the zone JSON object; returns 1 if the token can see no matching zone.
find_zone() {
  local name="$1" out
  while [[ "$name" == *.* ]]; do
    if out="$(cf_try GET "/zones?name=$name")" && [[ "$(jq '.result | length' <<<"$out")" -gt 0 ]]; then
      jq -c '.result[0]' <<<"$out"; return 0
    fi
    name="${name#*.}"
  done
  return 1
}

public_ip() { have dig && dig +short "$1" @1.1.1.1 2>/dev/null | grep -E '^[0-9.]+$' | head -1 || true; }
site_live() { # host: 0 if this Worker answers on it (resolved through public DNS, so stale local caches don't matter)
  local ip; ip="$(public_ip "$1")"
  if [[ -n "$ip" ]]; then curl -fsS -m 10 --resolve "$1:443:$ip" "https://$1/_/health" 2>/dev/null | grep -q '"ok":true'
  else curl -fsS -m 10 "https://$1/_/health" 2>/dev/null | grep -q '"ok":true'; fi
}

# Does this machine's admin token open the live Worker on HOST? Prints match | mismatch | missing | down.
admin_match() {
  local h="$1" tok ip url code
  tok="$(secret_get "$KC_ADMIN")"
  [[ -n "$tok" ]] || { echo missing; return 0; }
  url="${CLIENT_PAGE_BASE:-https://$h}/_admin/pages"
  ip=""; [[ -z "${CLIENT_PAGE_BASE:-}" ]] && ip="$(public_ip "$h")"
  if [[ -n "$ip" ]]; then
    code="$(printf 'header = "Authorization: Bearer %s"\n' "$tok" | curl -sS -m 10 -K - --resolve "$h:443:$ip" -o /dev/null -w '%{http_code}' "$url" 2>/dev/null || true)"
  else
    code="$(printf 'header = "Authorization: Bearer %s"\n' "$tok" | curl -sS -m 10 -K - -o /dev/null -w '%{http_code}' "$url" 2>/dev/null || true)"
  fi
  case "$code" in 2*) echo match ;; 401) echo mismatch ;; *) echo down ;; esac
}

# A hostname where this skill's Worker already answers on ACCOUNT (custom domain or workers.dev), if any.
existing_host() {
  local acc="$1" out hn sub
  if out="$(cf_try GET "/accounts/$acc/workers/domains")"; then
    hn="$(jq -r --arg s "$(worker_name)" '[.result[] | select(.service == $s)][0].hostname // empty' <<<"$out")"
    [[ -n "$hn" ]] && { printf '%s' "$hn"; return 0; }
  fi
  if out="$(cf_try GET "/accounts/$acc/workers/scripts/$(worker_name)/subdomain")" \
     && [[ "$(jq -r '.result.enabled' <<<"$out")" == true ]]; then
    sub="$(workers_dev_subdomain "$acc")"
    [[ -n "$sub" ]] && printf '%s' "$(worker_name).$sub.workers.dev"
  fi
  return 0
}

admin_import_guide() {
  cat <<EOF
      → The site was set up from another machine, which holds its admin token. Copy it here (it is never shown):
          1. On the machine that set the site up, copy the token to its clipboard:
               macOS:  security find-generic-password -a $KC_ACCOUNT -s $KC_ADMIN -w | pbcopy
               other:  the file ~/.config/client-page/$KC_ADMIN.secret
          2. Carry it over privately (a password manager, or Apple's Universal Clipboard).
          3. On this machine, save it (paste when asked; nothing is shown):
               $(save_secret_cmd "$KC_ADMIN")
          Then run doctor again.
      → If that machine is gone for good: $0 setup <address> --rotate-admin-token
        This makes a new admin token here; any other machine then needs it copied over the same way.
EOF
}

# ---------- doctor ----------

if [[ -t 1 ]]; then G=$'\033[32m'; R=$'\033[31m'; Y=$'\033[33m'; N=$'\033[0m'; else G=""; R=""; Y=""; N=""; fi
pass() { printf '  %s✓%s %s\n' "$G" "$N" "$*"; }
fail() { printf '  %s✗%s %s\n' "$R" "$N" "$*"; FAILS=$((FAILS + 1)); }
note() { printf '  %s•%s %s\n' "$Y" "$N" "$*"; }
next() { printf '      → %s\n' "$*"; }

install_hint() {
  case "$1" in
    jq) echo "macOS: brew install jq (or download from https://jqlang.org) · Debian/Ubuntu: sudo apt install jq · Windows: use WSL" ;;
    curl) echo "macOS has it · Debian/Ubuntu: sudo apt install curl" ;;
    openssl) echo "macOS has it · Debian/Ubuntu: sudo apt install openssl" ;;
    dig) echo "macOS has it · Debian/Ubuntu: sudo apt install dnsutils" ;;
    node) echo "https://nodejs.org (only needed to run the skill's tests)" ;;
    *) echo "macOS: brew install $1 · Debian/Ubuntu: sudo apt install $1" ;;
  esac
}

# ---------- tiers ----------
# Each tier includes the one before it. "free" needs no card; R2 and Zero Trust ask for a payment method.

tier_rank() { case "${1:-}" in free) echo 1 ;; media) echo 2 ;; full) echo 3 ;; *) echo 0 ;; esac; }
tier_ok() { [[ "$(tier_rank "${1:-}")" -gt 0 ]]; }
tier_label() { case "$1" in free) echo "free (pages)" ;; media) echo "media (pages + images and video)" ;; full) echo "full (pages + images and video + owner dashboard)" ;; esac; }
# The tier in force: the config's, else what this machine has already set up.
current_tier() {
  local t; t="$(conf_get tier)"
  if tier_ok "$t"; then printf '%s' "$t"; return 0; fi
  if [[ -n "$(conf_get access_aud)" ]]; then echo full
  elif [[ -n "$(conf_get files_bucket)" ]]; then echo media
  elif [[ -n "$(conf_get d1_id)" ]]; then echo free
  fi
}
raise_tier() { [[ "$(tier_rank "$1")" -le "$(tier_rank "$(current_tier)")" ]] || conf_set tier "$1"; }

cmd_tiers() {
  cat <<EOF
client-page tiers. Each tier includes everything in the one before it.

free: pages                                                   No card needed
  You get   Pages at a link on your own domain or a free *.workers.dev address.
            Visitors answer anonymously; answers are saved and read back through Claude.
            Lock, archive, give a page a new link, delete it.
            Small images (up to about 1.5 MB per page in total) built into the page itself.
  You do    Make a free Cloudflare account, and one API token (2 permission rows, 4 with your own domain).

media: + images and video                                     Card on file
  Adds      Screenshots, images, short videos and PDFs you upload with a page: up to 100 MB each,
            10 GB free. Visitors still can't upload anything.
  You do    Add a payment method to the Cloudflare account and turn on R2 (Cloudflare's file storage).
            The free allowance isn't charged. Plus 1 more token row.

full: + owner dashboard                                       Card on file
  Adds      https://<site>/admin behind a login with a code emailed to you: every page with its status,
            search, copy link, open, change link, delete.
  You do    Set up Cloudflare Zero Trust once (a team name and the Free plan, up to 50 users; it asks
            for a payment method too). Plus 2 more token rows.

Choose a tier and an address, then let doctor guide the rest:
  $0 doctor --tier free  docs.example.com     (your own domain, already on Cloudflare)
  $0 doctor --tier media --workers-dev        (no domain: Cloudflare's free address)
Moving up later is the same command with the higher tier; nothing is lost.
EOF
}

cf_account_guide() {
  cat <<EOF
      → No Cloudflare account yet? Sign up free at https://dash.cloudflare.com/sign-up (email and password,
        then confirm the email).
EOF
}

payment_guide() {
  cat <<EOF
      → Add a payment method (needed for R2 and Zero Trust; their free allowances aren't charged):
          https://dash.cloudflare.com → your account → Manage account → Billing → Payment info → add a card.
EOF
}

r2_enable_guide() {
  cat <<EOF
      → Turn on R2 once: https://dash.cloudflare.com → Storage & databases → R2 → follow the steps
        (pick the free plan if asked). It needs the payment method above.
EOF
}

zero_trust_guide() {
  cat <<EOF
      → Set up Zero Trust once: https://one.dash.cloudflare.com → choose a team name (e.g. your name or
        company) → Free plan. A one-time PIN login (code by email) is on by default.
EOF
}

domain_guide() {
  local zone="$1"
  cat <<EOF
      → The domain must be on a Cloudflare account and "Active". Either:
          • Buy one: https://dash.cloudflare.com → Domain Registration → Register Domains. It is Active at once.
          • Use one you own: https://dash.cloudflare.com → Add a domain → enter ${zone:-the domain} → Free plan.
            Cloudflare shows two nameservers; set them at the registrar where the domain was bought.
            The domain turns Active within minutes (sometimes up to a day). Then run doctor again.
      → No domain? Use Cloudflare's free address instead: $0 doctor --tier ${TIER_SEL:-free} --workers-dev
EOF
}

# token_rows TIER ZONE|"": the permission rows this tier and address need, one per line.
token_rows() {
  local tier="$1" zone="$2"
  echo "Account · Workers Scripts                                         · Edit"
  echo "Account · D1                                                      · Edit"
  [[ -n "$zone" ]] && echo "Zone    · Zone                                                    · Read   (zone: $zone)"
  [[ -n "$zone" ]] && echo "Zone    · Workers Routes                                          · Edit   (zone: $zone)"
  [[ "$(tier_rank "$tier")" -ge 2 ]] && echo "Account · Workers R2 Storage                                      · Edit"
  [[ "$(tier_rank "$tier")" -ge 3 ]] && echo "Account · Access: Apps and Policies                               · Edit"
  [[ "$(tier_rank "$tier")" -ge 3 ]] && echo "Account · Access: Organizations, Identity Providers, and Groups   · Edit"
  return 0
}

token_guide() {
  local tier="$1" zone="$2"
  cat <<EOF
      → Create a Cloudflare API token (about two minutes):
          1. Open https://dash.cloudflare.com/profile/api-tokens → Create Token → Custom token → Get started.
          2. Token name: client-page
          3. Permissions, one row each (use "+ Add more"):
$(token_rows "$tier" "$zone" | sed 's/^/               /')
          4. Account Resources: Include · your account.$([[ -n "$zone" ]] && printf '\n             Zone Resources: Include · Specific zone · %s.' "$zone")
          5. Continue to summary → Create Token → copy the token (Cloudflare shows it only once).
          6. Save it on this machine, in your own terminal. Paste when asked; nothing is shown:
               $(save_secret_cmd "$KC_CF")
EOF
}

# The whole first-time path for a tier, in order, for someone who has nothing yet.
onboarding_guide() {
  local tier="$1" zone="$2"
  echo "      Steps for the $tier tier, in order:"
  cf_account_guide
  if [[ "$(tier_rank "$tier")" -ge 2 ]]; then payment_guide; r2_enable_guide; fi
  [[ "$(tier_rank "$tier")" -ge 3 ]] && zero_trust_guide
  token_guide "$tier" "$zone"
}

# Prints the account id this setup uses: config, then CLIENT_PAGE_ACCOUNT_ID, then the token's only account.
# Returns 2 (after listing them on stderr) when the token sees several accounts.
find_account() {
  local a out n
  a="$(conf_get account_id)"; [[ -n "$a" ]] && { printf '%s' "$a"; return 0; }
  [[ -n "${CLIENT_PAGE_ACCOUNT_ID:-}" ]] && { printf '%s' "$CLIENT_PAGE_ACCOUNT_ID"; return 0; }
  out="$(cf_try GET "/accounts?per_page=50")" || return 1
  n="$(jq '.result | length' <<<"$out")"
  if [[ "$n" -eq 1 ]]; then jq -r '.result[0].id' <<<"$out"; return 0; fi
  if [[ "$n" -gt 1 ]]; then jq -r '.result[] | "        \(.id)  \(.name)"' <<<"$out" >&2; return 2; fi
  return 1
}

workers_dev_subdomain() { # ACCOUNT_ID → the account's <name> in <name>.workers.dev, or nothing
  local out; out="$(cf_try GET "/accounts/$1/workers/subdomain")" || return 0
  jq -r '.result.subdomain // empty' <<<"$out"
}

access_guide() {
  zero_trust_guide
  cat <<EOF
      → Edit the client-page API token (https://dash.cloudflare.com/profile/api-tokens) and add two rows:
          Account · Access: Apps and Policies                               · Edit
          Account · Access: Organizations, Identity Providers, and Groups   · Edit
        The token's value stays the same, so nothing needs saving again.
      Then run: $0 admin-setup you@example.com
EOF
}

# r2_state ACCOUNT_ID: on | off (R2 not turned on, usually no payment method) | denied (token lacks the row)
r2_state() {
  local out
  if out="$(cf_try GET "/accounts/$1/r2/buckets")"; then echo on; return 0; fi
  if grep -Eq '"code": ?10042[,}]' <<<"$out" || grep -qi "enable R2" <<<"$out"; then echo off
  elif grep -Eq '"code": ?(10000|9109|10001)[,}]' <<<"$out"; then echo denied
  else echo off; fi
}

# access_state ACCOUNT_ID: <team domain> | none (Zero Trust not set up) | denied (token lacks the row)
access_state() {
  local out team
  if out="$(cf_try GET "/accounts/$1/access/organizations")"; then
    team="$(jq -r '.result.auth_domain // empty' <<<"$out")"
    if [[ -n "$team" ]]; then echo "$team"; else echo none; fi
    return 0
  fi
  if grep -Eq '"code": ?(10000|9109|10001)[,}]' <<<"$out"; then echo denied; else echo none; fi
}

# doctor [--tier free|media|full] [HOST | --workers-dev] [--preflight] [--rotate-admin-token]
# Checks what the chosen tier needs, in order, and prints the next step for each gap.
# With --preflight (used by setup) it returns non-zero if setup can't succeed yet.
cmd_doctor() {
  local h="" wd=0 preflight=0 rotate=0 tier="" a
  while [[ $# -gt 0 ]]; do
    a="$1"; shift
    case "$a" in
      --preflight) preflight=1 ;; --workers-dev) wd=1 ;; --rotate-admin-token) rotate=1 ;;
      --tier) tier="${1:-}"; shift || true ;;
      --tier=*) tier="${a#--tier=}" ;;
      *) h="$a" ;;
    esac
  done
  if [[ -z "$h" && $wd -eq 0 ]]; then h="$(host)"; fi
  [[ "$h" == *.workers.dev ]] && wd=1
  [[ -n "$tier" ]] || tier="$(current_tier)"
  TIER_SEL="$tier"
  FAILS=0

  echo "Tools (no Cloudflare CLI is needed: this skill talks to Cloudflare with curl)"
  for t in curl jq openssl; do
    if have "$t"; then pass "$t"; else fail "$t is not installed"; next "$(install_hint "$t")"; fi
  done
  if have dig; then pass "dig"; else note "dig not found (optional; helps check DNS) · $(install_hint dig)"; fi
  if have node; then pass "node (for the skill's tests)"; else note "node not found (optional) · $(install_hint node)"; fi
  if have wrangler || have cloudflared; then note "wrangler/cloudflared are installed but not used; nothing to change"; fi
  pass "secrets are stored in $(where_secrets)"
  if [[ $FAILS -gt 0 ]]; then echo; echo "Install the missing tools, then run doctor again."; return 1; fi

  echo; echo "Tier"
  if [[ -z "$tier" ]]; then
    fail "no tier chosen yet"
    echo
    cmd_tiers | sed 's/^/    /'
    return 1
  fi
  if ! tier_ok "$tier"; then fail "unknown tier '$tier' (use free, media or full; see: $0 tiers)"; return 1; fi
  pass "$(tier_label "$tier")"

  echo; echo "Site address"
  local zone_guess=""
  if [[ $wd -eq 1 ]]; then
    pass "Cloudflare's free address: https://$(worker_name).<your-name>.workers.dev/<uuid>"
  elif [[ -z "$h" ]]; then
    fail "no address chosen yet. Two options:"
    next "Your own domain (looks best to clients): $0 doctor --tier $tier docs.example.com"
    next "No domain needed, Cloudflare's free address: $0 doctor --tier $tier --workers-dev"
    return 1
  elif [[ ! "$h" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$ ]]; then
    fail "'$h' isn't a valid hostname (lowercase letters, digits, dots and dashes)"; return 1
  else
    pass "pages will live at https://$h/<uuid>"
    zone_guess="$(sed -E 's/^[^.]+\.//' <<<"$h")"
  fi

  echo; echo "Cloudflare account and API token"
  if [[ -z "$(secret_get "$KC_CF")" ]]; then
    fail "no Cloudflare API token saved on this machine"
    onboarding_guide "$tier" "$zone_guess"
    echo; echo "Then run doctor again: $0 doctor --tier $tier $([[ $wd -eq 1 ]] && echo --workers-dev || echo "$h")"; return 1
  fi
  local v
  if v="$(cf_try GET /user/tokens/verify)" && [[ "$(jq -r '.result.status' <<<"$v")" == active ]]; then
    pass "token is active"
  else
    fail "the saved token was rejected ($(jq -r '.errors[0].message // .result.status // "unknown"' <<<"$v" 2>/dev/null))"
    next "It may be mistyped, expired or deleted. Create a new one and save it again:"
    token_guide "$tier" "$zone_guess"
    return 1
  fi

  local zone_json="" zone="" zone_id="" account_id="" rc=0
  if [[ $wd -eq 1 ]]; then
    account_id="$(find_account)" || rc=$?
    if [[ $rc -eq 2 ]]; then
      fail "this token can use several Cloudflare accounts (listed above)"
      next "Pick one and run: CLIENT_PAGE_ACCOUNT_ID=<id> $0 doctor --tier $tier --workers-dev  (setup the same way)"
      return 1
    elif [[ -z "$account_id" ]]; then
      fail "the token can't see any Cloudflare account"
      next "Edit the token so Account Resources includes your account:"
      token_guide "$tier" ""
      return 1
    fi
    pass "account $account_id"
    local sub; sub="$(workers_dev_subdomain "$account_id")"
    if [[ -n "$sub" ]]; then
      h="$(worker_name).$sub.workers.dev"
      pass "free address: https://$h/<uuid>"
    else
      fail "this account hasn't chosen its free workers.dev name yet"
      next "Open https://dash.cloudflare.com → Workers & Pages. The first visit asks you to pick a name"
      next "(for example your company name); pages then live at https://$(worker_name).<that-name>.workers.dev."
    fi
  else
    if zone_json="$(find_zone "$h")"; then
      zone="$(jq -r '.name' <<<"$zone_json")"; zone_id="$(jq -r '.id' <<<"$zone_json")"; account_id="$(jq -r '.account.id' <<<"$zone_json")"
      if [[ "$(jq -r '.status' <<<"$zone_json")" == active ]]; then
        pass "$zone is on Cloudflare and active"
      else
        fail "$zone is on Cloudflare but not active yet (status: $(jq -r '.status' <<<"$zone_json"))"
        next "At your registrar, set the nameservers to: $(jq -r '.name_servers | join(", ")' <<<"$zone_json")"
        next "Then wait for Cloudflare's \"Active\" email and run doctor again."
      fi
    else
      fail "no Cloudflare zone for $h is visible to this token"
      echo "      → Either the domain isn't on Cloudflare yet, or the token lacks Zone · Zone · Read for it."
      domain_guide "$zone_guess"
      next "If the domain is already Active, edit the token and add Zone · Zone · Read for that zone."
      return 1
    fi
  fi

  echo; echo "What the $tier tier needs"
  local before=$FAILS r2="" acc=""
  if cf_try GET "/accounts/$account_id/workers/scripts" >/dev/null; then pass "Workers (pages)"
  else fail "the token can't manage Workers"; next "Edit the token: add Account · Workers Scripts · Edit"; fi
  if cf_try GET "/accounts/$account_id/d1/database?per_page=1" >/dev/null; then pass "D1 (saved answers)"
  else fail "the token can't manage D1 databases"; next "Edit the token: add Account · D1 · Edit"; fi
  if [[ $wd -eq 0 ]]; then
    if cf_try GET "/zones/$zone_id/workers/routes" >/dev/null; then pass "Workers Routes on $zone (your address)"
    else fail "the token can't attach the Worker to $zone"; next "Edit the token: add Zone · Workers Routes · Edit for $zone"; fi
  fi
  if [[ "$(tier_rank "$tier")" -ge 2 ]]; then
    r2="$(r2_state "$account_id")"
    case "$r2" in
      on) pass "R2 (images and video) is on" ;;
      denied) fail "the token can't use R2"; next "Edit the token: add Account · Workers R2 Storage · Edit" ;;
      *) fail "R2 isn't turned on for this account yet"; payment_guide; r2_enable_guide ;;
    esac
  fi
  if [[ "$(tier_rank "$tier")" -ge 3 ]]; then
    acc="$(access_state "$account_id")"
    case "$acc" in
      denied) fail "the token can't read Zero Trust"; next "Edit the token: add the two Access rows below"; access_guide ;;
      none) fail "Zero Trust isn't set up for this account yet"; payment_guide; zero_trust_guide ;;
      *) pass "Zero Trust team $acc (dashboard login)" ;;
    esac
  fi
  [[ $FAILS -eq $before ]] || next "(Edit the token at https://dash.cloudflare.com/profile/api-tokens; its value stays the same.)"

  echo; echo "Address check"
  local live=0
  if [[ -z "$h" || "$h" == *"<"* ]]; then
    note "skipped until the workers.dev name exists"
  elif site_live "$h"; then
    live=1; pass "https://$h is serving this skill's Worker"
  elif [[ $wd -eq 1 ]]; then
    pass "https://$h will go live when setup runs"
  elif [[ -n "$(public_ip "$h")" ]]; then
    fail "$h already has a DNS record pointing somewhere else"
    next "In Cloudflare → $zone → DNS → Records, delete the record for ${h%%.$zone} (if it isn't used),"
    next "or choose another hostname, e.g. pages.$zone, and run: $0 doctor --tier $tier pages.$zone"
  else
    pass "$h is free (no DNS record yet); setup will create it"
  fi

  echo; echo "This machine"
  local admin_host="" adm=""
  if [[ $live -eq 1 ]]; then admin_host="$h"; elif [[ -n "$account_id" ]]; then admin_host="$(existing_host "$account_id")"; fi
  if [[ -n "$admin_host" ]]; then
    adm="$(admin_match "$admin_host")"
    case "$adm" in
      match) pass "admin token matches the live site (https://$admin_host)" ;;
      down) note "couldn't check the admin token: https://$admin_host didn't answer" ;;
      *)
        if [[ $rotate -eq 1 ]]; then
          note "setup will make a new admin token (--rotate-admin-token); other machines will need it copied over"
        elif [[ "$adm" == missing ]]; then
          fail "this skill's Worker is already live at https://$admin_host, but this machine has no admin token for it"
          admin_import_guide
        else
          fail "this machine's admin token doesn't open https://$admin_host (it was replaced from another machine)"
          admin_import_guide
        fi ;;
    esac
  elif [[ -n "$(secret_get "$KC_ADMIN")" ]]; then pass "admin token saved"
  else note "admin token not created yet (setup creates it)"; fi
  local configured=0
  if [[ -n "$h" && "$(host)" == "$h" && -n "$(conf_get d1_id)" ]]; then configured=1; pass "config for $h in $CONF"; else note "not set up for this address yet"; fi

  echo; echo "Features"
  local ready=$(( live == 1 && configured == 1 ))
  if [[ $ready -eq 1 ]]; then pass "Pages and saved answers: live at https://$h"; else note "Pages and saved answers: after setup"; fi
  local files_on=0 dash_on=0 nextstep=""
  if [[ "$(tier_rank "$tier")" -ge 2 ]]; then
    if [[ -n "$(conf_get files_bucket)" && $ready -eq 1 ]] && ( admin GET "/files" ) >/dev/null 2>&1; then files_on=1; pass "Images and video: on (R2 bucket $(conf_get files_bucket))"
    else note "Images and video: in your tier, not set up yet"; fi
  else
    note "Images and video: hosted files are in the media tier. On free, small images are built into the page."
  fi
  if [[ "$(tier_rank "$tier")" -ge 3 ]]; then
    if [[ -n "$(conf_get access_aud)" && $ready -eq 1 ]]; then
      local ip dash; ip="$(public_ip "$h")"
      if [[ -n "$ip" ]]; then dash="$(curl -s -m 10 --resolve "$h:443:$ip" -o /dev/null -w '%{http_code} %{redirect_url}' "https://$h/admin" 2>/dev/null || true)"
      else dash="$(curl -s -m 10 -o /dev/null -w '%{http_code} %{redirect_url}' "https://$h/admin" 2>/dev/null || true)"; fi
      case "$dash" in
        30[0-9]\ *cloudflareaccess.com*) dash_on=1; pass "Owner dashboard: https://$h/admin, login for $(conf_get admin_emails)" ;;
        *) fail "Owner dashboard: https://$h/admin isn't behind the Cloudflare login (got: ${dash:-no answer})"; next "Run: $0 admin-setup $(conf_get admin_emails)" ;;
      esac
    else note "Owner dashboard: in your tier, not set up yet"; fi
  else
    note "Owner dashboard: in the full tier (see: $0 tiers)"
  fi

  echo
  local setup_arg="$h"; [[ $wd -eq 1 ]] && setup_arg="--workers-dev"
  if [[ $FAILS -gt 0 ]]; then
    echo "Fix the ✗ items above, then run doctor again."; return 1
  fi
  if [[ $ready -eq 0 || "$adm" != match ]]; then
    [[ $rotate -eq 1 ]] && setup_arg="$setup_arg --rotate-admin-token"
    nextstep="$0 setup --tier $tier $setup_arg"
  elif [[ "$(tier_rank "$tier")" -ge 2 && $files_on -eq 0 ]]; then nextstep="$0 files-setup"
  elif [[ "$(tier_rank "$tier")" -ge 3 && $dash_on -eq 0 ]]; then nextstep="$0 admin-setup you@example.com"
  fi
  if [[ $preflight -eq 1 ]]; then return 0; fi
  if [[ -n "$nextstep" ]]; then echo "Ready. Next: $nextstep"
  else echo "All set for the $tier tier. Publish a page with: $0 publish page.html"; fi
  return 0
}

# ---------- commands ----------

apply_schema() {
  local account_id db_id; account_id="$(require_conf account_id)"; db_id="$(require_conf d1_id)"
  local n=0
  local out
  while IFS= read -r stmt; do
    if out="$(cf_try POST "/accounts/$account_id/d1/database/$db_id/query" -H 'content-type: application/json' \
        --data "$(jq -n --argjson s "$stmt" '{sql: $s}')")"; then
      n=$((n + 1))
    elif grep -qi "duplicate column name" <<<"$out"; then
      n=$((n + 1))   # an ADD COLUMN that this database already has
    else
      jq -r '(.errors // []) | map("  Cloudflare: \(.code) \(.message)") | join("\n")' <<<"$out" >&2 2>/dev/null || true
      die "schema statement failed: $(jq -r . <<<"$stmt" | head -c 80)…"
    fi
  done < <(sed 's/--.*$//' "$SKILL_DIR/worker/schema.sql" \
    | jq -Rsc 'split(";") | map(gsub("^\\s+|\\s+$"; "")) | map(select(length > 0)) | .[]')
  echo "Schema applied ($n statements)"
}

# setup HOST          use the user's own domain (custom domain on their Cloudflare zone)
# setup --workers-dev use Cloudflare's free <worker>.<name>.workers.dev address
cmd_setup() {
  local h="" wd=0 rotate=0 tier="" a
  while [[ $# -gt 0 ]]; do
    a="$1"; shift
    case "$a" in
      --workers-dev) wd=1 ;; --rotate-admin-token) rotate=1 ;;
      --tier) tier="${1:-}"; shift || true ;;
      --tier=*) tier="${a#--tier=}" ;;
      *) h="$a" ;;
    esac
  done
  [[ -n "$tier" ]] || tier="$(current_tier)"
  if ! tier_ok "$tier"; then
    cmd_tiers
    die "choose a tier first: $0 doctor --tier free|media|full <address>"
  fi
  if [[ -z "$h" && $wd -eq 0 ]]; then h="$(host)"; fi
  [[ "$h" == *.workers.dev ]] && wd=1
  if [[ -z "$h" && $wd -eq 0 ]]; then
    die "usage: $0 setup --tier $tier docs.<your-domain>   or   $0 setup --tier $tier --workers-dev   (run doctor first)"
  fi
  local doctor_args=("$h"); [[ $wd -eq 1 ]] && doctor_args=(--workers-dev)
  [[ $rotate -eq 1 ]] && doctor_args+=(--rotate-admin-token)
  echo "Checking prerequisites…"
  # setup itself only needs what every tier needs; the tier's extras are checked by files-setup / admin-setup.
  cmd_doctor --tier free "${doctor_args[@]}" --preflight >/dev/null \
    || { cmd_doctor --tier "$tier" "${doctor_args[@]}" || true; die "setup stopped before changing anything: fix the ✗ items above"; }

  local zone_id="" account_id
  if [[ $wd -eq 1 ]]; then
    account_id="$(find_account)"
    h="$(worker_name).$(workers_dev_subdomain "$account_id").workers.dev"
    echo "Using Cloudflare's free address https://$h"
  else
    local z; z="$(find_zone "$h")"
    zone_id="$(jq -r '.id' <<<"$z")"; account_id="$(jq -r '.account.id' <<<"$z")"
    echo "Zone $(jq -r '.name' <<<"$z") found"
  fi
  conf_set host "$h"; conf_set zone_id "$zone_id"; conf_set account_id "$account_id"
  conf_set worker "$(worker_name)"; conf_set d1_name "$NAME_DEFAULT"
  conf_set address "$([[ $wd -eq 1 ]] && echo workers.dev || echo custom-domain)"

  local d db_id
  d="$(cf GET "/accounts/$account_id/d1/database?name=$NAME_DEFAULT")"
  db_id="$(jq -r --arg n "$NAME_DEFAULT" '[.result[] | select(.name == $n)][0].uuid // empty' <<<"$d")"
  if [[ -z "$db_id" ]]; then
    db_id="$(cf POST "/accounts/$account_id/d1/database" -H 'content-type: application/json' \
      --data "$(jq -n --arg n "$NAME_DEFAULT" '{name: $n}')" | jq -r '.result.uuid')"
    echo "Created D1 database '$NAME_DEFAULT'"
  else
    echo "Using existing D1 database '$NAME_DEFAULT'"
  fi
  conf_set d1_id "$db_id"
  apply_schema

  if [[ $rotate -eq 1 ]]; then
    secret_set_random "$KC_ADMIN"
    echo "Made a new admin token in $(where_secrets); other machines need it copied over before they can publish"
    cmd_deploy --rotate-admin-token
  else
    if [[ -z "$(secret_get "$KC_ADMIN")" ]]; then
      secret_set_random "$KC_ADMIN"
      echo "Created the admin token in $(where_secrets)"
    fi
    cmd_deploy
  fi

  if [[ $wd -eq 1 ]]; then
    cf POST "/accounts/$account_id/workers/scripts/$(worker_name)/subdomain" -H 'content-type: application/json' \
      --data '{"enabled": true, "previews_enabled": false}' >/dev/null && echo "workers.dev address enabled"
  else
    cf POST "/accounts/$account_id/workers/scripts/$(worker_name)/subdomain" -H 'content-type: application/json' \
      --data '{"enabled": false}' >/dev/null && echo "workers.dev address disabled (the custom domain is the only way in)"
    cf PUT "/accounts/$account_id/workers/domains" -H 'content-type: application/json' \
      --data "$(jq -n --arg h "$h" --arg s "$(worker_name)" --arg z "$zone_id" \
        '{hostname: $h, service: $s, zone_id: $z, environment: "production"}')" >/dev/null
    echo "Custom domain https://$h attached"
  fi

  # Resolve through public DNS: the machine caches the "no such host" it saw before the record existed.
  printf 'Waiting for https://%s to answer' "$h"
  for _ in $(seq 1 45); do
    if site_live "$h"; then
      echo " ok"
      curl -fsS -m 10 "https://$h/_/health" >/dev/null 2>&1 \
        || echo "(This machine may still have an old DNS answer cached for a few minutes.)"
      conf_set tier "$tier"
      echo "Done: pages are live on the $tier tier."
      case "$tier" in
        media) echo "Next, turn on images and video: $0 files-setup" ;;
        full) echo "Next, turn on images and video: $0 files-setup"
              echo "Then the owner dashboard:      $0 admin-setup you@example.com" ;;
        *) echo "Publish a page with: $0 publish page.html" ;;
      esac
      return 0
    fi
    printf '.'; sleep 4
  done
  echo; die "https://$h isn't answering yet; DNS and the certificate can take a few minutes. Check with: $0 doctor"
}

# deploy [--rotate-admin-token]: uploads worker/ with this machine's admin token. Without the flag it refuses
# when the live site answers to a different admin token, because uploading would replace that token.
cmd_deploy() {
  need curl; need jq
  local account_id db_id; account_id="$(require_conf account_id)"; db_id="$(require_conf d1_id)"
  [[ -n "$(secret_get "$KC_ADMIN")" ]] || die "no admin token saved; run: $0 doctor"
  if [[ "${1:-}" != --rotate-admin-token ]]; then
    local live_host; live_host="$(conf_get host)"
    if [[ -n "$live_host" ]] && { [[ -n "${CLIENT_PAGE_BASE:-}" ]] || site_live "$live_host"; }; then
      case "$(admin_match "$live_host")" in
        match|down) ;;
        *) admin_import_guide >&2
           die "deploy stopped: this machine's admin token doesn't open https://$live_host, and deploying would replace it" ;;
      esac
    fi
  fi
  local tmp; tmp="$(mktemp -d)"
  ( umask 077
    printf '%s' "$(secret_get "$KC_ADMIN")" >"$tmp/admin"
    jq -n --arg db "$db_id" --rawfile tok "$tmp/admin" --arg date "$COMPAT_DATE" \
      --arg team "$(conf_get access_team)" --arg aud "$(conf_get access_aud)" --arg emails "$(conf_get admin_emails)" \
      --arg bucket "$(conf_get files_bucket)" '{
      main_module: "worker.mjs",
      compatibility_date: $date,
      bindings: ([
        {type: "d1", name: "DB", id: $db},
        {type: "secret_text", name: "ADMIN_TOKEN", text: $tok}
      ] + (if $aud == "" then [] else [
        {type: "plain_text", name: "ACCESS_TEAM", text: $team},
        {type: "plain_text", name: "ACCESS_AUD", text: $aud},
        {type: "plain_text", name: "ADMIN_EMAILS", text: $emails}
      ] end)
        + (if $bucket == "" then [] else [{type: "r2_bucket", name: "FILES", bucket_name: $bucket}] end))
    }' >"$tmp/metadata.json"
    rm -f "$tmp/admin" )
  # Every module in worker/ is uploaded; worker.mjs is the entry point.
  local parts=(-F "metadata=@$tmp/metadata.json;type=application/json") f
  for f in "$SKILL_DIR"/worker/*.mjs; do
    parts+=(-F "$(basename "$f")=@$f;filename=$(basename "$f");type=application/javascript+module")
  done
  local status=0
  cf PUT "/accounts/$account_id/workers/scripts/$(worker_name)" "${parts[@]}" >/dev/null || status=$?
  rm -rf "$tmp"
  [[ $status -eq 0 ]] || exit $status
  echo "Deployed Worker '$(worker_name)'"
}

# admin-setup EMAIL[,EMAIL…]: puts a Cloudflare Access login in front of https://<site>/admin, lets only these
# emails in, and redeploys the Worker so it checks the login itself too.
cmd_admin_setup() {
  local emails="${1:-}" e list=()
  [[ -n "$emails" ]] || die "usage: $0 admin-setup you@example.com[,someone@example.com]"
  emails="$(tr 'A-Z' 'a-z' <<<"$emails" | tr -d ' ')"
  IFS=',' read -r -a list <<<"$emails"
  for e in "${list[@]}"; do [[ "$e" =~ ^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$ ]] || die "not an email address: $e"; done
  local h account_id; h="$(require_host)"; account_id="$(require_conf account_id)"

  local team
  team="$(access_state "$account_id")"
  case "$team" in
    denied) echo "  ✗ The API token can't read Zero Trust yet." >&2; access_guide >&2; die "admin-setup stopped before changing anything" ;;
    none) echo "  ✗ Cloudflare Zero Trust isn't set up for this account yet." >&2; payment_guide >&2; access_guide >&2; die "admin-setup stopped before changing anything" ;;
  esac
  echo "Zero Trust team: $team"

  local apps app_id body out aud include
  apps="$(cf_try GET "/accounts/$account_id/access/apps?per_page=100")" \
    || { access_guide >&2; die "the token can't manage Access applications; add the rows in step 2 above"; }
  app_id="$(jq -r --arg d "$h/admin" '[.result[] | select(.domain == $d)][0].id // empty' <<<"$apps")"
  include="$(printf '%s\n' "${list[@]}" | jq -R '{email: {email: .}}' | jq -s '.')"
  body="$(jq -n --arg d "$h/admin" --arg n "client-page dashboard ($h)" --argjson inc "$include" '{
    name: $n, domain: $d, type: "self_hosted", session_duration: "24h", app_launcher_visible: false,
    policies: [{name: "Dashboard owners", decision: "allow", include: $inc}]
  }')"
  if [[ -n "$app_id" ]]; then
    out="$(cf PUT "/accounts/$account_id/access/apps/$app_id" -H 'content-type: application/json' --data "$body")"
    echo "Updated the Access login for https://$h/admin"
  else
    out="$(cf POST "/accounts/$account_id/access/apps" -H 'content-type: application/json' --data "$body")"
    echo "Created the Access login for https://$h/admin"
  fi
  aud="$(jq -r '.result.aud // empty' <<<"$out")"
  [[ -n "$aud" ]] || die "Cloudflare didn't return the application's audience tag"

  # The login needs a sign-in method; the simplest is a one-time PIN emailed to the allowed address.
  local idps
  if idps="$(cf_try GET "/accounts/$account_id/access/identity_providers")" \
     && [[ "$(jq '[.result[]? | select(.type == "onetimepin")] | length' <<<"$idps")" -eq 0 ]]; then
    if cf_try POST "/accounts/$account_id/access/identity_providers" -H 'content-type: application/json' \
         --data '{"name": "One-time PIN", "type": "onetimepin", "config": {}}' >/dev/null; then
      echo "Added the one-time PIN login (Cloudflare emails a code to the allowed address)"
    elif [[ "$(jq '.result | length' <<<"$idps")" -eq 0 ]]; then
      echo "  • No login method is set up, and this token can't add one. In https://one.dash.cloudflare.com →"
      echo "    Integrations → Identity providers → Add new identity provider → One-time PIN → Save."
    fi
  fi

  conf_set access_team "$team"; conf_set access_aud "$aud"; conf_set admin_emails "$emails"
  raise_tier full
  cmd_deploy
  echo "Dashboard ready: https://$h/admin"
  echo "Sign in with $(sed 's/,/ or /g' <<<"$emails"); Cloudflare emails a one-time code. Opening https://$h while signed in goes there too."
}

# ---------- files (images, video, audio, PDF) ----------

FILE_EXT_RE='\.(png|jpe?g|gif|webp|avif|svg|mp4|webm|mov|mp3|m4a|wav|ogg|pdf)$'

mime_of() {
  case "$(tr 'A-Z' 'a-z' <<<"${1##*.}")" in
    png) echo image/png ;; jpg|jpeg) echo image/jpeg ;; gif) echo image/gif ;; webp) echo image/webp ;;
    avif) echo image/avif ;; svg) echo image/svg+xml ;; mp4) echo video/mp4 ;; webm) echo video/webm ;;
    mov) echo video/quicktime ;; mp3) echo audio/mpeg ;; m4a) echo audio/mp4 ;; wav) echo audio/wav ;;
    ogg) echo audio/ogg ;; pdf) echo application/pdf ;; *) return 1 ;;
  esac
}

sha256_of() { if have shasum; then shasum -a 256 "$1" | cut -c1-64; else sha256sum "$1" | cut -c1-64; fi; }

r2_guide() {
  echo "      Hosted images and video are the media tier (see: $0 tiers). They use Cloudflare R2: 10 GB free."
  payment_guide
  r2_enable_guide
  cat <<EOF
      → Edit the client-page API token (https://dash.cloudflare.com/profile/api-tokens) and add:
          Account · Workers R2 Storage · Edit
      Then run: $0 files-setup
EOF
}

# upload_file FILE: stores FILE once (same content, same address) and prints its path, /_/f/<hash>/<name>.
upload_file() {
  local f="$1" type sha name key code tok
  [[ -f "$f" ]] || die "no such file: $f"
  type="$(mime_of "$f")" || die "not an image, video, audio file or PDF: $f"
  [[ "$(wc -c <"$f" | tr -d ' ')" -le 104857600 ]] || die "$f is over 100 MB; host big videos elsewhere (e.g. an unlisted YouTube link)"
  sha="$(sha256_of "$f")"
  name="$(basename "$f" | sed -E 's/[^A-Za-z0-9._-]+/-/g; s/^-+//' | cut -c1-120)"
  [[ -n "$name" ]] || name="file.${f##*.}"
  key="${sha:0:12}/$name"
  if [[ "$(curl -s -o /dev/null -w '%{http_code}' -I "$(site)/_/f/$key")" == 200 ]]; then
    echo "  = $f (already uploaded)" >&2
  else
    tok="$(secret_get "$KC_ADMIN")"; [[ -n "$tok" ]] || die "no admin token saved; run: $0 doctor"
    code="$(printf 'header = "Authorization: Bearer %s"\n' "$tok" | curl -sS -K - -X PUT -H "content-type: $type" \
      --data-binary "@$f" -o /dev/null -w '%{http_code}' "$(site)/_admin/files/$key")" || die "upload failed: $f"
    case "$code" in
      2*) echo "  ↑ $f" >&2 ;;
      501) r2_guide >&2; die "file storage isn't set up yet" ;;
      *) die "upload of $f answered HTTP $code" ;;
    esac
  fi
  printf '/_/f/%s\n' "$key"
}

cmd_upload() {
  [[ $# -gt 0 ]] || die "usage: $0 upload FILE [FILE …]   (prints each file's public URL)"
  local f p
  for f in "$@"; do p="$(upload_file "$f")" || exit 1; echo "$(site)$p"; done
}

# rewrite_assets HTML BASE_DIR OUT: uploads every local image/video/PDF the page refers to by a relative
# path (src=, data-src=, href=, poster=), six at a time, and writes a copy of the page with those links
# pointing at the uploaded files. Prints the number of files.
rewrite_assets() {
  local html="$1" base="$2" out="$3" refs ref n=0 work mode=upload type
  work="$(mktemp -d)"
  # Without file storage (the free tier) images are built into the page as data: URLs instead.
  [[ -n "$(conf_get files_bucket)" ]] || mode=inline
  refs="$(grep -oE "(src|data-src|href|poster)=(\"[^\"]*\"|'[^']*')" "$html" | sed -E "s/^[a-z-]+=//; s/^[\"']//; s/[\"']\$//" | sort -u || true)"
  while IFS= read -r ref; do
    [[ -n "$ref" ]] || continue
    case "$ref" in http:*|https:*|//*|/*|\#*|data:*|blob:*|mailto:*|tel:*|javascript:*) continue ;; esac
    grep -qiE "$FILE_EXT_RE" <<<"$ref" || continue
    [[ -f "$base/$ref" ]] || { echo "  ! $ref is referenced but not found next to the page; left as is" >&2; continue; }
    printf '%s\0' "$ref" >>"$work/refs"
    n=$((n + 1))
  done <<<"$refs"
  : >"$work/map.tsv"
  if [[ $n -gt 0 && $mode == upload ]]; then
    # Each worker prints "<ref>\t<path>"; any failed upload makes xargs fail, and the publish stops.
    xargs -0 -n 1 -P 6 "$0" _upload-one "$base" <"$work/refs" >"$work/map.tsv" \
      || { rm -rf "$work"; echo "client-page: an upload failed (see above); nothing was published" >&2; exit 1; }
  elif [[ $n -gt 0 ]]; then
    while IFS= read -r -d '' ref; do
      type="$(mime_of "$base/$ref")"
      case "$type" in
        image/*) printf '%s\tdata:%s;base64,%s\n' "$ref" "$type" "$(base64 <"$base/$ref" | tr -d '\n')" >>"$work/map.tsv" ;;
        *) rm -rf "$work"
           echo "client-page: $ref is a ${type#*/} file. Video, audio and PDF need hosted files, which are the media tier." >&2
           echo "  See: $0 tiers   then: $0 files-setup" >&2
           exit 1 ;;
      esac
    done <"$work/refs"
  fi
  jq -Rn '[inputs | select(length > 0) | split("\t") | {(.[0]): .[1]}] | add // {}' <"$work/map.tsv" >"$work/map.json"
  jq -Rrs --slurpfile mm "$work/map.json" '$mm[0] as $m | reduce ($m | to_entries[]) as $e (.;
      split("\"" + $e.key + "\"") | join("\"" + $e.value + "\"")
    | split("\u0027" + $e.key + "\u0027") | join("\u0027" + $e.value + "\u0027"))' "$html" >"$out"
  rm -rf "$work"
  echo "$n $mode"
}

# Internal, used by rewrite_assets through xargs: _upload-one BASE_DIR REF
cmd_upload_one() {
  local p; p="$(upload_file "$1/$2")" || exit 1
  printf '%s\t%s\n' "$2" "$p"
}

cmd_files() {
  admin GET "/files" | jq -r '.files[] | [.url, .type, "\(.size / 1024 | floor) KB"] | @tsv'
}

cmd_rm_file() {
  [[ -n "${1:-}" ]] || die "usage: $0 rm-file <hash>/<name>   (as shown by: $0 files)"
  admin DELETE "/files/${1#/_/f/}" >/dev/null && echo "Removed ${1#/_/f/}"
}

# files-setup: creates the R2 bucket and connects it to the Worker, so pages can show images and video.
cmd_files_setup() {
  local account_id out bucket="client-page-files"
  account_id="$(require_conf account_id)"
  case "$(r2_state "$account_id")" in
    denied) echo "  ✗ The API token can't use R2 yet." >&2; r2_guide >&2; die "files-setup stopped before changing anything" ;;
    off) echo "  ✗ R2 isn't turned on for this Cloudflare account yet (it needs a payment method on file)." >&2; r2_guide >&2; die "files-setup stopped before changing anything" ;;
  esac
  out="$(cf GET "/accounts/$account_id/r2/buckets")"
  if [[ "$(jq --arg b "$bucket" '[.result.buckets[]? | select(.name == $b)] | length' <<<"$out")" -eq 0 ]]; then
    cf POST "/accounts/$account_id/r2/buckets" -H 'content-type: application/json' --data "{\"name\": \"$bucket\"}" >/dev/null
    echo "Created R2 bucket '$bucket'"
  else
    echo "Using R2 bucket '$bucket'"
  fi
  conf_set files_bucket "$bucket"
  raise_tier media
  cmd_deploy
  # A new Worker version takes a few seconds to reach every Cloudflare location.
  local i
  for i in 1 2 3 4 5 6 7 8 9 10; do
    if ( admin GET "/files" ) >/dev/null 2>&1; then
      echo "File storage ready. Publish pages that use images with: $0 publish page.html"; return 0
    fi
    sleep 3
  done
  die "the Worker doesn't see the bucket yet; wait a minute and run: $0 doctor"
}

cmd_health() {
  local out; out="$(curl -sS "$(site)/_/health")" || die "$(site) unreachable; run: $0 doctor"
  echo "$out"
}

decode_entities() { sed -e 's/&lt;/</g' -e 's/&gt;/>/g' -e 's/&quot;/"/g' -e "s/&#39;/'/g" -e 's/&amp;/\&/g'; }

cmd_publish() {
  need jq
  local file="" id="" title="" mode="" description="" assets=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --id) id="$2"; shift 2 ;;
      --title) title="$2"; shift 2 ;;
      --description) description="$2"; shift 2 ;;
      --assets) assets="$2"; shift 2 ;;
      --no-assets) assets="-"; shift ;;
      --mode) mode="$2"; shift 2 ;;
      -*) die "unknown option $1" ;;
      *) file="$1"; shift ;;
    esac
  done
  [[ -n "$file" && -f "$file" ]] || die "usage: publish FILE.html [--id UUID] [--title TEXT] [--description TEXT] [--mode open|locked] [--assets DIR | --no-assets]"
  [[ -z "$id" ]] || uuid_ok "$id"
  [[ -z "$mode" || "$mode" == open || "$mode" == locked ]] || die "--mode is open or locked"
  if [[ -z "$title" ]]; then
    title="$(grep -o -m1 '<title>[^<]*</title>' "$file" | sed 's/<[^>]*>//g' | decode_entities || true)"
  fi
  local tmp; tmp="$(mktemp -d)"
  local src="$file" n
  if [[ "$assets" != "-" ]]; then
    n="$(rewrite_assets "$file" "${assets:-$(dirname "$file")}" "$tmp/page.html")" || { rm -rf "$tmp"; exit 1; }
    src="$tmp/page.html"
    case "$n" in
      "0 "*) ;;
      *" upload") echo "Linked ${n% *} file(s) from the page to their uploaded copies" >&2 ;;
      *" inline") echo "Built ${n% *} image(s) into the page (free tier: no hosted files)" >&2
        if [[ "$(wc -c <"$src" | tr -d ' ')" -gt 1800000 ]]; then
          rm -rf "$tmp"
          die "with its images built in, the page is over the 1.8 MB limit. Use smaller images (e.g. JPEG, under 1200 px wide), or move up to the media tier: $0 tiers"
        fi ;;
    esac
  fi
  jq -n --rawfile html "$src" --arg title "$title" --arg mode "$mode" --arg description "$description" \
    '{html: $html, title: $title}
     + (if $mode == "" then {} else {mode: $mode} end)
     + (if $description == "" then {} else {description: $description} end)' >"$tmp/body.json"
  local out
  if [[ -n "$id" ]]; then out="$(admin PUT "/pages/$id" "$tmp/body.json")"
  else out="$(admin POST "/pages" "$tmp/body.json")"; fi
  rm -rf "$tmp"
  jq -r '"\(.url)\n  title:       \(.title)\n  description: \(.description // "")\n  version:     \(.version)\n  mode:        \(.mode)\n  " + (if .created then "new page" else "updated in place; saved answers kept" end)' <<<"$out"
}

cmd_list() {
  admin GET "/pages" | jq -r '.pages[] | [
      .id, .mode, "v\(.version)", "\(.records) saved",
      (.updated_at / 1000 | strftime("%Y-%m-%d %H:%M")),
      (if .archived_at then "ARCHIVED" else "" end), .title
    ] | @tsv'
}

cmd_get() { uuid_ok "$1"; admin GET "/pages/$1" | jq '.'; }
cmd_html() { uuid_ok "$1"; admin GET "/pages/$1?html=1" | jq -r '.html'; }

cmd_records() {
  uuid_ok "$1"
  if [[ -n "${2:-}" ]]; then admin GET "/pages/$1/records?collection=$2" | jq '.'
  else admin GET "/pages/$1/records" | jq '.'; fi
}

patch_page() {
  uuid_ok "$1"
  local tmp; tmp="$(mktemp)"; printf '%s' "$2" >"$tmp"
  admin PATCH "/pages/$1" "$tmp" | jq -r '"\(.url): ok"'
  rm -f "$tmp"
}

cmd_new_link() {
  uuid_ok "${1:-}"
  admin POST "/pages/$1/new-link" | jq -r '"New link: \(.url)\n  The old link (\(.old)) no longer works; saved answers moved with the page."'
}

# delete UUID --yes: removes the page, its saved answers and the uploaded files only it uses. Permanent.
cmd_delete() {
  local id="" yes=0 a
  for a in "$@"; do case "$a" in --yes) yes=1 ;; *) id="$a" ;; esac; done
  uuid_ok "$id"
  [[ $yes -eq 1 ]] || die "delete is permanent (the page, its saved answers and files only it uses). Re-run with --yes: $0 delete $id --yes   (to just hide it: $0 archive $id)"
  admin DELETE "/pages/$id" | jq -r '"Deleted \(.deleted): \(.records) saved entries removed, \(.filesDeleted) files deleted, \(.filesKept) kept because other pages use them."'
}

cmd_rm_record() {
  uuid_ok "$1"; [[ -n "${2:-}" && -n "${3:-}" ]] || die "usage: rm-record UUID COLLECTION DOC_ID"
  admin DELETE "/pages/$1/records/$2/$3" >/dev/null && echo "Removed $2/$3"
}

usage() {
  cat <<EOF
Usage: $(basename "$0") <command> [args]

Getting started (no Cloudflare CLI needed):
  tiers                        what each tier gives you and needs (free: no card; media and full: card on file)
  doctor --tier T ADDRESS      check what tier T needs and print the next step for each gap.
                               ADDRESS is docs.example.com (your domain) or --workers-dev (free address)
  setup --tier T ADDRESS       one-time: database, schema, admin token, Worker, address
  setup … --rotate-admin-token replace the site's admin token from this machine (when the machine that set it up is gone)
                               (setup refuses to start until doctor passes; with no argument both reuse
                               the address already set up)

Images and video (optional):
  files-setup                  turn on file storage (Cloudflare R2) so pages can show images, video, audio, PDF
  upload FILE [FILE …]         upload files yourself and print their URLs
  files                        list uploaded files
  rm-file HASH/NAME            remove one uploaded file
                               publish uploads any image/video a page links to by a relative path, by itself

Owner dashboard (optional):
  admin-setup EMAIL[,EMAIL]    list every page at https://<site>/admin, behind a Cloudflare login for these emails

Pages:
  publish FILE [--id UUID] [--title T] [--description D] [--mode open|locked]
                               new page (prints its URL), or update one in place with --id
  list                         every page: id, mode, version, saved answers, title
  get UUID                     page details
  html UUID                    print the page's current HTML
  records UUID [COLLECTION]    dump saved answers as JSON
  lock UUID | unlock UUID      stop or resume accepting answers
  archive UUID | restore UUID  hide the page from visitors, or bring it back (nothing is deleted)
  new-link UUID                give the page a new uuid; the old link stops working, answers move with it
  delete UUID --yes            delete the page, its answers and files only it uses, for good
  rm-record UUID COLLECTION ID remove one saved document (e.g. a test probe)

Maintenance:
  deploy                       upload the Worker again after editing worker/ (refuses if this machine's admin
                               token doesn't match the live site; see doctor)
  schema                       re-apply worker/schema.sql (idempotent)
  health                       check the site answers
  verify                       same as doctor
EOF
}

main() {
  local cmd="${1:-}"; shift || true
  case "$cmd" in
    doctor|verify) cmd_doctor "$@" ;;
    tiers) cmd_tiers ;;
    setup) cmd_setup "$@" ;;
    deploy) cmd_deploy "$@" ;;
    admin-setup) cmd_admin_setup "$@" ;;
    files-setup) cmd_files_setup ;;
    upload) cmd_upload "$@" ;;
    _upload-one) cmd_upload_one "${1:-}" "${2:-}" ;;
    files) cmd_files ;;
    rm-file) cmd_rm_file "${1:-}" ;;
    schema) apply_schema ;;
    health) cmd_health ;;
    publish) cmd_publish "$@" ;;
    list) cmd_list ;;
    get) cmd_get "${1:-}" ;;
    html) cmd_html "${1:-}" ;;
    records) cmd_records "${1:-}" "${2:-}" ;;
    lock) patch_page "${1:-}" '{"mode":"locked"}' ;;
    unlock) patch_page "${1:-}" '{"mode":"open"}' ;;
    archive) patch_page "${1:-}" '{"archived":true}' ;;
    restore) patch_page "${1:-}" '{"archived":false}' ;;
    rm-record) cmd_rm_record "${1:-}" "${2:-}" "${3:-}" ;;
    new-link) cmd_new_link "${1:-}" ;;
    delete) cmd_delete "$@" ;;
    ""|-h|--help|help) usage ;;
    *) usage; exit 1 ;;
  esac
}

main "$@"
